version: "3"

services:
  bioartbot-dashboard:
    image: node:14.17.3-alpine
    container_name: bioartbot-dashboard
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      NODE_ENV: ${NODE_ENV}
      VUE_APP_BACKEND_API_URL: ${VUE_APP_BACKEND_API_URL}
      VUE_APP_FRONTEND_URL: ${VUE_APP_FRONTEND_URL}
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
